### ISSUE TITLE
Parse Error-Section3

### ISSUE THREAD

**Issue by ShaylynHM** [ShaylynHM/prefers-accessibility#1]
I'm not sure what this parse error is referring to? I tried removing the bracket but it doesn't seem to work...
@anna-pokhilenko
<img width="849" alt="Screen Shot 2021-11-22 at 7 30 03 PM" src="https://user-images.githubusercontent.com/77545465/142954811-db48645c-c2ac-4a99-8bf4-c9f840c1490f.png">
ko

**Comment by anna-pokhilenko** [comment]
You forgot to close the first two media queries. That is why everything is getting messed up. Add an additoional } at the end of the first two MQs and you should be good!
